# Generated by Django 4.1.3 on 2022-12-03 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seleccion', '0005_asociacion_equipos'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='capitan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seleccion.jugador'),
        ),
    ]
