# Generated by Django 4.1.3 on 2022-12-03 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seleccion', '0006_equipo_capitan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asociacion',
            name='equipos',
        ),
    ]
