# Generated by Django 4.1.3 on 2022-12-03 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seleccion', '0007_remove_asociacion_equipos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='capitan',
        ),
    ]
