# Generated by Django 4.1.3 on 2022-12-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seleccion', '0009_asociacion_equipos_equipo_capitan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='club',
            field=models.IntegerField(),
        ),
    ]
