# Generated by Django 4.1.3 on 2022-12-03 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seleccion', '0010_alter_jugador_club'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jugador',
            old_name='club',
            new_name='edad',
        ),
    ]
